version: '3'

services:
  eth_net:
    build: .
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ../:/workspace
    command: /bin/bash -c "cd /workspace/simulation && exec invoke run_ropsten"